const factualInstructions = `Write an English weather briefing for the supplied 24-hour window using ONLY the supplied hourly forecast. Give 2–3 sentences, at most 75 words, in plain text. Cover the temperature trend/range, precipitation timing and chance, and notable changes only when the data supports them. The listed precipitation probability belongs to its displayed interval. Missing values are unknown, never zero. Preserve uncertainty: probability is not a promise. Do not invent amounts, wind forecasts, warnings, official alerts, or exact onset times. Do not extrapolate outside the supplied window. Use the supplied local day/time labels and temperature unit. Avoid relative phrases like "in an hour" that become misleading in a cached summary. Include one everyday practical takeaway if justified. No heading, markdown, greeting, sign-off, or mention of being an AI.`;
const personalities = { 'warm-practical': 'Speak warmly and naturally, like a helpful neighbor. Use simple dayparts such as this evening, overnight, and tomorrow afternoon; avoid full dates, timezone abbreviations, and unnecessary minute precision. Focus on the most useful change, not an inventory of intervals. Group low precipitation chances together instead of listing every small peak. Never say "supplied window", "listed intervals", or describe your input data. Keep advice practical and restrained; no game jargon, jokes, or alarmism.' };

export const briefingInstructions = `${factualInstructions}\n${personalities['warm-practical']}`;
const sentenceSegmenter = new Intl.Segmenter('en', { granularity: 'sentence' });

export function validSummary(text: string): boolean {
  if (!text || text.length > 1600 || text.split(/\s+/).length > 75) return false;
  const sentences = [...sentenceSegmenter.segment(text)].filter(part => part.segment.trim());
  return sentences.length >= 2 && sentences.length <= 3;
}

export const appleBriefingInstructions = `Write a warm, practical English weather briefing from these calculated facts only. Produce exactly two sentences totaling at most 75 words. Describe the temperature range and change, and precipitation chance and timing. Use the given temperature unit. Add a brief everyday takeaway only when supported. A null value is unknown. When missingTemperatureHours or temperature.missingHours is positive, describe only the available readings. When missingPrecipitationHours is positive, explicitly state that precipitation data is incomplete; never claim dry weather or no chance of precipitation across the window. A probability is not a promise. Use natural local dayparts. Do not add a greeting, heading, or sign-off. Never invent numbers, rain amounts, wind, warnings, or exact onset times. If all precipitation chances are known and zero, say no rain is forecast; never introduce a nonzero chance. Only use numeric temperatures and probabilities present in the facts.`;
